package andrewl.videowall.DataBase.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wallDataDaoConfig;

    private final WallDataDao wallDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wallDataDaoConfig = daoConfigMap.get(WallDataDao.class).clone();
        wallDataDaoConfig.initIdentityScope(type);

        wallDataDao = new WallDataDao(wallDataDaoConfig, this);

        registerDao(WallData.class, wallDataDao);
    }
    
    public void clear() {
        wallDataDaoConfig.getIdentityScope().clear();
    }

    public WallDataDao getWallDataDao() {
        return wallDataDao;
    }

}
