package andrewl.videowall.DataBase.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table T_WallData.
*/
public class WallDataDao extends AbstractDao<WallData, Long> {

    public static final String TABLENAME = "T_WallData";

    /**
     * Properties of entity WallData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Date = new Property(1, java.util.Date.class, "date", false, "DATE");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property LocalPicAddr = new Property(3, String.class, "localPicAddr", false, "LOCAL_PIC_ADDR");
        public final static Property RemotePicAddr = new Property(4, String.class, "remotePicAddr", false, "REMOTE_PIC_ADDR");
        public final static Property LocalVideoAddr = new Property(5, String.class, "localVideoAddr", false, "LOCAL_VIDEO_ADDR");
        public final static Property RemoteVideoAddr = new Property(6, String.class, "remoteVideoAddr", false, "REMOTE_VIDEO_ADDR");
    };


    public WallDataDao(DaoConfig config) {
        super(config);
    }
    
    public WallDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'T_WallData' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'DATE' INTEGER," + // 1: date
                "'NAME' TEXT," + // 2: name
                "'LOCAL_PIC_ADDR' TEXT," + // 3: localPicAddr
                "'REMOTE_PIC_ADDR' TEXT," + // 4: remotePicAddr
                "'LOCAL_VIDEO_ADDR' TEXT," + // 5: localVideoAddr
                "'REMOTE_VIDEO_ADDR' TEXT);"); // 6: remoteVideoAddr
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'T_WallData'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, WallData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(2, date.getTime());
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String localPicAddr = entity.getLocalPicAddr();
        if (localPicAddr != null) {
            stmt.bindString(4, localPicAddr);
        }
 
        String remotePicAddr = entity.getRemotePicAddr();
        if (remotePicAddr != null) {
            stmt.bindString(5, remotePicAddr);
        }
 
        String localVideoAddr = entity.getLocalVideoAddr();
        if (localVideoAddr != null) {
            stmt.bindString(6, localVideoAddr);
        }
 
        String remoteVideoAddr = entity.getRemoteVideoAddr();
        if (remoteVideoAddr != null) {
            stmt.bindString(7, remoteVideoAddr);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public WallData readEntity(Cursor cursor, int offset) {
        WallData entity = new WallData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)), // date
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // localPicAddr
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // remotePicAddr
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // localVideoAddr
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // remoteVideoAddr
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, WallData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDate(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLocalPicAddr(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRemotePicAddr(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLocalVideoAddr(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRemoteVideoAddr(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(WallData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(WallData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
